// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecases/get_temperature_by_cep.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecases/get_temperature_by_cep.go -destination ./internal/usecases/mocks/get_temperature_by_cep.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	usecases "github.com/arfurlaneto/goexpert-challenge-temperature-by-cep/internal/usecases"
	gomock "go.uber.org/mock/gomock"
)

// MockGetTemperatureByCepUseCase is a mock of GetTemperatureByCepUseCase interface.
type MockGetTemperatureByCepUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetTemperatureByCepUseCaseMockRecorder
}

// MockGetTemperatureByCepUseCaseMockRecorder is the mock recorder for MockGetTemperatureByCepUseCase.
type MockGetTemperatureByCepUseCaseMockRecorder struct {
	mock *MockGetTemperatureByCepUseCase
}

// NewMockGetTemperatureByCepUseCase creates a new mock instance.
func NewMockGetTemperatureByCepUseCase(ctrl *gomock.Controller) *MockGetTemperatureByCepUseCase {
	mock := &MockGetTemperatureByCepUseCase{ctrl: ctrl}
	mock.recorder = &MockGetTemperatureByCepUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetTemperatureByCepUseCase) EXPECT() *MockGetTemperatureByCepUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetTemperatureByCepUseCase) Execute(ctx context.Context, input *usecases.TemperatureByCepInput) (*usecases.TemperatureByCepOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*usecases.TemperatureByCepOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetTemperatureByCepUseCaseMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetTemperatureByCepUseCase)(nil).Execute), ctx, input)
}
